[app]
# LLM used for internal operations, like deriving conversation names
fast_llm = "azure/gpt-4o"

# LLM used for user-facing output, like RAG replies
quality_llm = "azure/gpt-4o"

# LLM used for ingesting visual inputs
vlm = "azure/gpt-4o"

# LLM used for transcription
audio_lm = "azure/whisper-1"

[embedding]
base_model = "azure/text-embedding-3-large"

[completion_embedding]
base_model = "azure/text-embedding-3-large"

[database]
  [database.graph_creation_settings]
    clustering_mode = "remote"

[ingestion]
provider = "unstructured_local"
strategy = "auto"
chunking_strategy = "by_title"
new_after_n_chars = 2_048
max_characters = 4_096
combine_under_n_chars = 1_024
overlap = 128
document_summary_model = "azure/gpt-4o"
vision_img_model = "azure/gpt-4o"
vision_pdf_model = "azure/gpt-4o"
automatic_extraction = true # enable automatic extraction of entities and relations

  [ingestion.extra_parsers]
    pdf = "zerox"

  [ingestion.chunk_enrichment_settings]
    generation_config = { model = "azure/gpt-4o" }

[orchestration]
provider = "simple"
